### ISSUE TITLE
Other roles into #sufficient?, #accept?, #valid?

### ISSUE THREAD

**Issue by kachick** [kachick/striuct#25]
I want this

今は全部同じ意味を持たせているが、それぞれ使いたいシーン違う気してきたので、0.n以降では変えたい
now(0.2.0)
# sufficient?(name, value=self[name])

alias #accept?, #valid?

modify(0.4.0~?)
# sufficient?(name, value=self[name])
# accept?(name, value)
# valid?(name)

**Comment by EherKuramkan1** [comment]
#59
