### ISSUE TITLE
Deal option instead of condition if condition is a Hash

### ISSUE THREAD

**Issue by kachick** [kachick/striuct#63]
オプション引数だけでつかいたいような状況を当初想定していなかったゆえのダサいAPIをなんとかしたい

Hash自体をConditionにしたいなんていうことはまずないだろうと思うので、2引数目Hash時はオプション扱いにしたい

ようは、こういうのからださいANYTHING?をとっぱらいたい

``` ruby
Foo = Striuct.define do
  member :foo, ANYTHING?, default: :bar
end
```

こう使いたい

``` ruby
Foo = Striuct.define do
  member :foo, default: :bar
end
```

conditionもオプション引数送りにするのは変更点多いので、妥協案として

**Comment by EherKuramkan1** [comment]
#59
